APP_TITLE = "BT Sensor Config Tool"
DEBUG = True

DEFAULT_BAUDRATE = 115200
SERIAL_TIMEOUT_S = 0.8

CMD_READ_CAL_USER = 0x00
CMD_WRITE_CAL_USER = 0x01
CMD_READ_BOARD_USER = 0x02
CMD_WRITE_BOARD_USER = 0x03
CMD_READ_TEXT_USER = 0x04
CMD_WRITE_TEXT_USER = 0x05

CMD_READ_CAL_FACTORY = 0x10
CMD_WRITE_CAL_FACTORY = 0x11
CMD_READ_BOARD_FACTORY = 0x12
CMD_WRITE_BOARD_FACTORY = 0x13
CMD_READ_TEXT_FACTORY = 0x14
CMD_WRITE_TEXT_FACTORY = 0x15

CMD_RESTORE_FACTORY = 0xF0

SENSOR_INDEX = 0

CAL_POINTS = 10
DEADBAND_ROWS = 5
DEADBAND_COLS = 3

TEXT_GAS_LEN = 16
TEXT_SN_LEN = 32
TEXT_INFO_LEN = 32

BOARD_FIELD_SELFSET = 0
BOARD_FIELD_TEMP_WAY = 1
BOARD_FIELD_GAIN = 2
BOARD_FIELD_FACTORY_TIME = 3
BOARD_FIELD_LAST_MAINTAIN_TIME = 4

TEXT_FIELD_GAS = 0
TEXT_FIELD_BOARD_SN = 1
TEXT_FIELD_SENSOR_SN = 2
TEXT_FIELD_INFO = 3

CAL_FIELD_BIAODING_X = 0
CAL_FIELD_BIAODING_Y = 1
CAL_FIELD_XIANXING_X = 2
CAL_FIELD_XIANXING_Y = 3
CAL_FIELD_WENDU_X = 4
CAL_FIELD_WENDU_Y = 5
CAL_FIELD_DEADBAND = 6
CAL_FIELD_XIANXING_SW = 7
CAL_FIELD_WENDU_SW = 8
CAL_FIELD_DEADBAND_SW = 9

SCOPE_USER = "user"
SCOPE_FACTORY = "factory"
